import streamlit as st
st.title("Hi Aiml E")
st.write("hello aiml")
st.header("worldcup")
st.subheader("india")
st.text_input("enter your name")
st.number_input("enter your age")
st.slider("age",0,100)
st.checkbox("i agree all terms and conditions")
st.markdown("#this is a markdown header")
st.checkbox("check me out")
st.text_area("Enter a long text")
st.radio("choose an option",["option A","option B","option C"])
num=st.selectbox("select an option",["option A","option B","option C"])
st.write(f"you selected:{num}")
st.sidebar.write("this is sidebar")
st.sidebar.selectbox("menu",["A","B","C"])
with st.form("my form"):
    st.write("inside the form")
    name=st.text_input("name")
    age=st.number_input("age")
    password=st.text_input("password",type="password")
    text=st.text_area("additional informaion")
    st.snow()
    st.balloons()
    submitted = st.form_submit_button("Submit")
    if submitted:
        st.write(f"name:{name},age:{age}")
st.date_input("selecta a date")
st.time_input("select a time")
st.color_picker("select a color")
st.markdown("---")